import type { Lead, Client } from '$lib/api';

export interface ContactEvent {
	id: string;
	type: string;
	notes: string | null;
	created_at: string;
}

export const DEMO_LEADS: Lead[] = [
	// cold
	{
		id: 'a1b2c3d4-0001-4000-8000-aabbccddeef1',
		business_name: 'Pembina Pho',
		address: '1842 Pembina Hwy, Winnipeg, MB',
		phone: '(204) 555-0191',
		website_url: null,
		google_place_id: 'demo_pembina_pho',
		google_rating: 4.2,
		review_count: 47,
		has_gbp: true,
		has_website: false,
		has_https: false,
		pagespeed_mobile: null,
		pagespeed_desktop: null,
		mobile_friendly: null,
		site_age_estimate: null,
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: null,
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: null,
		pagespeed_best_practices: null,
		lead_score: 91,
		priority: 'high',
		status: 'cold',
		latitude: 49.8451,
		longitude: -97.1567,
		notes: null,
		hidden: false,
		created_at: '2026-01-10T10:00:00Z',
		last_updated: '2026-01-10T10:00:00Z'
	},
	{
		id: 'a1b2c3d4-0002-4000-8000-aabbccddeef2',
		business_name: 'Prairie Bloom Florist',
		address: '620 Academy Rd, Winnipeg, MB',
		phone: '(204) 555-0344',
		website_url: 'https://prairieblooms.ca',
		google_place_id: 'demo_prairie_bloom',
		google_rating: 4.6,
		review_count: 83,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 22,
		pagespeed_desktop: 61,
		mobile_friendly: false,
		site_age_estimate: '2019',
		also_on_yelp: true,
		yelp_url: 'https://www.yelp.com/biz/prairie-bloom-florist-winnipeg',
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'hello@prairieblooms.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: 74,
		pagespeed_best_practices: 68,
		lead_score: 67,
		priority: 'medium',
		status: 'cold',
		latitude: 49.8902,
		longitude: -97.1654,
		notes: null,
		hidden: false,
		created_at: '2026-01-12T11:00:00Z',
		last_updated: '2026-01-12T11:00:00Z'
	},
	{
		id: 'a1b2c3d4-0003-4000-8000-aabbccddeef3',
		business_name: 'Osborne Tattoo Co',
		address: '155 Osborne St, Winnipeg, MB',
		phone: '(204) 555-0822',
		website_url: null,
		google_place_id: 'demo_osborne_tattoo',
		google_rating: 4.8,
		review_count: 29,
		has_gbp: true,
		has_website: false,
		has_https: false,
		pagespeed_mobile: null,
		pagespeed_desktop: null,
		mobile_friendly: null,
		site_age_estimate: null,
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: null,
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: null,
		pagespeed_best_practices: null,
		lead_score: 88,
		priority: 'high',
		status: 'cold',
		latitude: 49.8771,
		longitude: -97.1437,
		notes: null,
		hidden: false,
		created_at: '2026-01-14T09:30:00Z',
		last_updated: '2026-01-14T09:30:00Z'
	},
	// contacted
	{
		id: 'a1b2c3d4-0004-4000-8000-aabbccddeef4',
		business_name: 'Forks Fitness Studio',
		address: '291 Main St, Winnipeg, MB',
		phone: '(204) 555-0133',
		website_url: 'https://forksfitness.ca',
		google_place_id: 'demo_forks_fitness',
		google_rating: 4.3,
		review_count: 112,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 31,
		pagespeed_desktop: 55,
		mobile_friendly: false,
		site_age_estimate: '2018',
		also_on_yelp: true,
		yelp_url: 'https://www.yelp.com/biz/forks-fitness-studio-winnipeg',
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'info@forksfitness.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: 62,
		pagespeed_best_practices: 58,
		lead_score: 74,
		priority: 'medium',
		status: 'contacted',
		latitude: 49.8988,
		longitude: -97.1347,
		notes: 'Reached out via email on Jan 20.',
		hidden: false,
		created_at: '2026-01-15T14:00:00Z',
		last_updated: '2026-01-20T08:00:00Z'
	},
	{
		id: 'a1b2c3d4-0005-4000-8000-aabbccddeef5',
		business_name: 'Cathedral Bakery',
		address: '510 Cathedral Ave, Winnipeg, MB',
		phone: '(204) 555-0477',
		website_url: null,
		google_place_id: 'demo_cathedral_bakery',
		google_rating: 4.9,
		review_count: 8,
		has_gbp: true,
		has_website: false,
		has_https: false,
		pagespeed_mobile: null,
		pagespeed_desktop: null,
		mobile_friendly: null,
		site_age_estimate: null,
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: null,
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: null,
		pagespeed_best_practices: null,
		lead_score: 95,
		priority: 'high',
		status: 'contacted',
		latitude: 49.9021,
		longitude: -97.1589,
		notes: 'Dropped in, spoke with owner briefly.',
		hidden: false,
		created_at: '2026-01-16T10:00:00Z',
		last_updated: '2026-01-22T09:00:00Z'
	},
	{
		id: 'a1b2c3d4-0006-4000-8000-aabbccddeef6',
		business_name: 'West End Auto Repair',
		address: '902 Ellice Ave, Winnipeg, MB',
		phone: '(204) 555-0655',
		website_url: 'https://www.skipthedishes.com/west-end-auto',
		google_place_id: 'demo_west_end_auto',
		google_rating: 4.1,
		review_count: 64,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 18,
		pagespeed_desktop: 42,
		mobile_friendly: false,
		site_age_estimate: null,
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: null,
		website_inferred: true,
		website_screenshot: null,
		pagespeed_seo: 44,
		pagespeed_best_practices: 47,
		lead_score: 82,
		priority: 'high',
		status: 'contacted',
		latitude: 49.8901,
		longitude: -97.1712,
		notes: null,
		hidden: false,
		created_at: '2026-01-17T13:00:00Z',
		last_updated: '2026-01-23T11:00:00Z'
	},
	// proposal
	{
		id: 'a1b2c3d4-0007-4000-8000-aabbccddeef7',
		business_name: 'Sage & Salt Spa',
		address: '47 Lilac St, Winnipeg, MB',
		phone: '(204) 555-0211',
		website_url: 'https://sageandsalt.ca',
		google_place_id: 'demo_sage_salt_spa',
		google_rating: 4.7,
		review_count: 201,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 44,
		pagespeed_desktop: 71,
		mobile_friendly: true,
		site_age_estimate: '2020',
		also_on_yelp: true,
		yelp_url: 'https://www.yelp.com/biz/sage-and-salt-spa-winnipeg',
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'book@sageandsalt.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: 81,
		pagespeed_best_practices: 75,
		lead_score: 71,
		priority: 'medium',
		status: 'proposal',
		latitude: 49.8812,
		longitude: -97.1523,
		notes: 'Sent proposal Feb 3. Waiting on response.',
		hidden: false,
		created_at: '2026-01-20T09:00:00Z',
		last_updated: '2026-02-03T16:00:00Z'
	},
	{
		id: 'a1b2c3d4-0008-4000-8000-aabbccddeef8',
		business_name: 'Corydon Cycle',
		address: '788 Corydon Ave, Winnipeg, MB',
		phone: '(204) 555-0389',
		website_url: null,
		google_place_id: 'demo_corydon_cycle',
		google_rating: 4.5,
		review_count: 37,
		has_gbp: true,
		has_website: false,
		has_https: false,
		pagespeed_mobile: null,
		pagespeed_desktop: null,
		mobile_friendly: null,
		site_age_estimate: null,
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: null,
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: null,
		pagespeed_best_practices: null,
		lead_score: 89,
		priority: 'high',
		status: 'proposal',
		latitude: 49.8733,
		longitude: -97.1678,
		notes: 'Proposal sent Feb 10. Very interested.',
		hidden: false,
		created_at: '2026-01-22T11:00:00Z',
		last_updated: '2026-02-10T14:00:00Z'
	},
	// closed_won
	{
		id: 'a1b2c3d4-0009-4000-8000-aabbccddeef9',
		business_name: 'Fort Rouge Physiotherapy',
		address: '233 Nassau St N, Winnipeg, MB',
		phone: '(204) 555-0544',
		website_url: 'https://fortrougephysio.ca',
		google_place_id: 'demo_fort_rouge_physio',
		google_rating: 4.8,
		review_count: 156,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 52,
		pagespeed_desktop: 78,
		mobile_friendly: true,
		site_age_estimate: '2021',
		also_on_yelp: true,
		yelp_url: 'https://www.yelp.com/biz/fort-rouge-physiotherapy-winnipeg',
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'dana@fortrougephysio.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: 88,
		pagespeed_best_practices: 82,
		lead_score: 78,
		priority: 'medium',
		status: 'closed_won',
		latitude: 49.8654,
		longitude: -97.1489,
		notes: 'Built booking site. Signed March 2026.',
		hidden: false,
		created_at: '2026-01-25T10:00:00Z',
		last_updated: '2026-03-01T08:00:00Z'
	},
	{
		id: 'a1b2c3d4-0010-4000-8000-aabbccddee10',
		business_name: 'Wolseley Coffee',
		address: '91 Wolseley Ave, Winnipeg, MB',
		phone: '(204) 555-0712',
		website_url: null,
		google_place_id: 'demo_wolseley_coffee',
		google_rating: 4.7,
		review_count: 5,
		has_gbp: true,
		has_website: false,
		has_https: false,
		pagespeed_mobile: null,
		pagespeed_desktop: null,
		mobile_friendly: null,
		site_age_estimate: null,
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'marcus@wolseleycoffee.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: null,
		pagespeed_best_practices: null,
		lead_score: 93,
		priority: 'high',
		status: 'closed_won',
		latitude: 49.8923,
		longitude: -97.1601,
		notes: 'Starter site. Launched April 2026.',
		hidden: false,
		created_at: '2026-01-28T09:00:00Z',
		last_updated: '2026-04-15T10:00:00Z'
	},
	// closed_lost
	{
		id: 'a1b2c3d4-0011-4000-8000-aabbccddee11',
		business_name: 'Exchange Eats',
		address: '100 Arthur St, Winnipeg, MB',
		phone: '(204) 555-0198',
		website_url: 'https://exchangeeats.ca',
		google_place_id: 'demo_exchange_eats',
		google_rating: 3.9,
		review_count: 312,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 61,
		pagespeed_desktop: 82,
		mobile_friendly: true,
		site_age_estimate: '2017',
		also_on_yelp: true,
		yelp_url: 'https://www.yelp.com/biz/exchange-eats-winnipeg',
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'info@exchangeeats.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: 84,
		pagespeed_best_practices: 79,
		lead_score: 55,
		priority: 'low',
		status: 'closed_lost',
		latitude: 49.8998,
		longitude: -97.1322,
		notes: 'Not interested. Already working with an agency.',
		hidden: false,
		created_at: '2026-01-30T14:00:00Z',
		last_updated: '2026-02-15T10:00:00Z'
	},
	{
		id: 'a1b2c3d4-0012-4000-8000-aabbccddee12',
		business_name: 'Transcona Printing',
		address: '3121 Pembina Hwy, Winnipeg, MB',
		phone: '(204) 555-0901',
		website_url: 'https://transconaprint.ca',
		google_place_id: 'demo_transcona_printing',
		google_rating: 4.0,
		review_count: 88,
		has_gbp: true,
		has_website: true,
		has_https: true,
		pagespeed_mobile: 58,
		pagespeed_desktop: 74,
		mobile_friendly: true,
		site_age_estimate: '2016',
		also_on_yelp: false,
		yelp_url: null,
		facebook_url: null,
		instagram_url: null,
		twitter_url: null,
		linkedin_url: null,
		tiktok_url: null,
		youtube_url: null,
		email: 'orders@transconaprint.ca',
		website_inferred: false,
		website_screenshot: null,
		pagespeed_seo: 77,
		pagespeed_best_practices: 71,
		lead_score: 48,
		priority: 'low',
		status: 'closed_lost',
		latitude: 49.8512,
		longitude: -97.1598,
		notes: 'Budget constraints. Follow up in 6 months.',
		hidden: false,
		created_at: '2026-02-01T10:00:00Z',
		last_updated: '2026-02-20T09:00:00Z'
	}
];

export const DEMO_CLIENTS: Client[] = [
	{
		id: 'c1d2e3f4-0001-4000-8000-aabbccddeec1',
		lead_id: 'a1b2c3d4-0009-4000-8000-aabbccddeef9',
		business_name: 'Fort Rouge Physiotherapy',
		contact_name: 'Dana Kowalski',
		phone: '(204) 555-0544',
		email: 'dana@fortrougephysio.ca',
		address: '233 Nassau St N, Winnipeg, MB',
		service_website: true,
		service_hosting: true,
		service_tools: false,
		mrr: 150,
		project_value: 1400,
		contract_start: '2026-03-01',
		notes: 'Built standard site with booking integration. On standard maintenance plan.',
		created_at: '2026-03-01T08:00:00Z'
	},
	{
		id: 'c1d2e3f4-0002-4000-8000-aabbccddeec2',
		lead_id: 'a1b2c3d4-0010-4000-8000-aabbccddee10',
		business_name: 'Wolseley Coffee',
		contact_name: 'Marcus Tran',
		phone: '(204) 555-0712',
		email: 'marcus@wolseleycoffee.ca',
		address: '91 Wolseley Ave, Winnipeg, MB',
		service_website: true,
		service_hosting: true,
		service_tools: false,
		mrr: 75,
		project_value: 800,
		contract_start: '2026-04-15',
		notes: 'Starter site. Owner wanted something clean and fast. Very easy project.',
		created_at: '2026-04-15T10:00:00Z'
	}
];

export const DEMO_CONTACT_EVENTS: Record<string, ContactEvent[]> = {
	'a1b2c3d4-0009-4000-8000-aabbccddeef9': [
		{
			id: 'e1f2a3b4-0001-4000-8000-aabbccddee01',
			type: 'note',
			notes: 'Site launched. Dana left a Google review unprompted.',
			created_at: '2026-02-21T09:00:00Z'
		},
		{
			id: 'e1f2a3b4-0002-4000-8000-aabbccddee02',
			type: 'call',
			notes: 'Dana confirmed she wants to proceed. Deposit incoming.',
			created_at: '2026-02-17T14:00:00Z'
		},
		{
			id: 'e1f2a3b4-0003-4000-8000-aabbccddee03',
			type: 'email',
			notes: 'Sent follow-up with proposal attached.',
			created_at: '2026-02-14T10:00:00Z'
		},
		{
			id: 'e1f2a3b4-0004-4000-8000-aabbccddee04',
			type: 'visit',
			notes: 'Stopped in, spoke with Dana directly. She was frustrated her old site had no booking form.',
			created_at: '2026-02-14T10:00:00Z'
		}
	],
	'a1b2c3d4-0010-4000-8000-aabbccddee10': [
		{
			id: 'e1f2a3b4-0005-4000-8000-aabbccddee05',
			type: 'note',
			notes: 'Site launched. Marcus left a Google review unprompted.',
			created_at: '2026-04-20T11:00:00Z'
		},
		{
			id: 'e1f2a3b4-0006-4000-8000-aabbccddee06',
			type: 'call',
			notes: 'Quick call, no objections. Sent invoice same day.',
			created_at: '2026-04-01T13:00:00Z'
		},
		{
			id: 'e1f2a3b4-0007-4000-8000-aabbccddee07',
			type: 'visit',
			notes: 'Walked in cold. Marcus was behind the counter, grabbed a coffee first.',
			created_at: '2026-03-28T10:00:00Z'
		}
	]
};

export const DEMO_MRR_OVER_TIME: { month: string; mrr: number }[] = [
	{ month: '2026-01', mrr: 0 },
	{ month: '2026-02', mrr: 0 },
	{ month: '2026-03', mrr: 150 },
	{ month: '2026-04', mrr: 225 },
	{ month: '2026-05', mrr: 225 },
	{ month: '2026-06', mrr: 225 }
];

export const DEMO_PIPELINE_FUNNEL: { status: string; count: number }[] = [
	{ status: 'cold', count: 3 },
	{ status: 'contacted', count: 3 },
	{ status: 'proposal', count: 2 },
	{ status: 'closed_won', count: 2 },
	{ status: 'closed_lost', count: 2 }
];

export const DEMO_REVENUE_BY_MONTH: { month: string; revenue: number }[] = [
	{ month: '2026-03', revenue: 1400 },
	{ month: '2026-04', revenue: 800 }
];
